name:                dhall-fly
version:             0.1.0.0
github:              "akshaymankar/dhall-fly"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/dhall-fly#readme>

dependencies:
- aeson
- aeson-casing
- base >= 4.7 && < 5
- bytestring
- containers
- dhall
- dhall-json
- either
- scientific
- template-haskell
- text
- unordered-containers
- vector
- yaml

library:
  source-dirs: src

executables:
  dhall-fly:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-fly

tests:
  dhall-fly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-fly
    - hspec
