name:                dhall-fly
version:             0.2.1
github:              "akshaymankar/dhall-fly"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"
category:            "Concourse, YAML, JSON, Dhall"
synopsis:            "Translate concourse config from Dhall to YAML"

extra-source-files:
- README.md
- ChangeLog.md
- dhall-concourse/**/*
- test/data/*.dhall

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/dhall-fly#readme>

dependencies:
- aeson                >=1.4.5.0
- aeson-casing         >=0.2.0.0
- base                 >= 4.7      && < 5
- dhall                >= 1.27.0   && < 1.28
- scientific           >=0.3.6.2
- text                 >=1.2.3.1
- transformers         >=0.5.6.2
- unordered-containers >=0.2.10.0
- ordered-containers   >=0.2.2
- vector               >=0.12.0.3
- optparse-applicative

library:
  source-dirs: src
  ghc-options:
  - -Wall

executables:
  dhall-fly:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - aeson-yaml >=1.0.3.0
    - bytestring >=0.10.8.2
    - dhall-fly
    - dhall-json >= 1.5.0   && < 1.6

tests:
  dhall-fly-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dhall-fly
    - hspec
    build-tools:
    - hspec-discover
