name: Haskell CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ["8.2.2", "8.4.4", "8.6.5", "8.8.1"]
        cabal: ["3.0"]

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{matrix.ghc}}
        cabal-version: ${{matrix.cabal}}
    - name: Install dependencies
      run: |
        cabal v2-install hpack
        hpack
        cabal v2-update
        cabal v2-install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal configure --enable-tests
        cabal v2-build
    - name: Run tests
      run: cabal v2-test
