name: Build and Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - windows-latest
        - macOS-latest

    runs-on: ${{matrix.platform}}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Install stack
      run: |
        curl -sSL https://get.haskellstack.org/ | sh

    - name: Install dependencies
      run: |
        stack setup --no-terminal --system-ghc
        stack build --no-terminal --system-ghc --test --no-run-tests --dependencies-only

    - name: Build
      run: stack build --no-terminal --system-ghc

    - name: Run tests
      run: stack test --no-terminal --system-ghc
