name: Build and Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform:
        - ubuntu-latest
        - windows-latest
        - macos-latest

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - uses: actions/setup-haskell@v1
      with:
        ghc-version: "8.6.5"

    - name: Install dependencies
      run: |
        stack setup --no-terminal --system-ghc
        stack build --no-terminal --system-ghc --test --no-run-tests --dependencies-only

    - name: Build
      run: stack build --no-terminal --system-ghc

    - name: Run tests
      run: stack test --no-terminal --system-ghc
